version: '3'

services:
  mysql:
    image: yobasystems/alpine-mariadb:latest
    # image: mysql:8.0
    container_name: wordpress-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - dbmysql:/var/lib/mysql
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    # command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - website

  memcached:
    image: memcached:latest

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    depends_on:
      - mysql
    links:
      - mysql
      - memcached:memcached
    restart: unless-stopped
    ports:
      - "8989:80"
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./wordpress/:/var/www/html
    networks:
      - website

volumes:
  dbmysql:

networks:
  website:
    driver: bridge
